@startuml

left to right direction

Actor "Контент-Менеджер" as admin 
note top of admin :Контент-Менеджер сайта

(Просмотр списка брендов) as (brandsList)
(Добавить новый бренд) as (brandAdd)
(Редактировать бренд) as (brandRedact)
(Удаление бренда) as (brandDelete)
(Прикрепить коллекцию) as (linkCollection)

admin -- brandsList

    brandsList <.- brandAdd :<<extend>>
    brandsList <.- brandRedact :<<extend>>
    brandsList <.- brandDelete :<<extend>>

    brandAdd -.> linkCollection :<<include>>
    brandRedact -.> linkCollection :<<include>>
@enduml