@startuml

title Процесс мульти-продуктовой \n обработки заявки на кредитную-карту

|Сервис-Адаптер|
    start
    ->[**POST api/v1/application/create**];
    :Сохранить заявку со статусом = CREATED;  
    :Выхов для получения данных о клиенте>

|CRM|
    
if(Клиент существует?) then (Да)
    :Извлечь профиль;
    else(Нет)
    :Запросить воркфлоу создания;
    :Создать карточку;
endif

    :Отправить данные>

|Сервис-Адаптер|

    :Данные получены<
    :Запрос рекомендаций>

|Система рекомендаций|

    :Получить запрос данных<
    :Создать рекомендации;
    :Отправить список рекомендованных продуктов>

|Сервис-Адаптер|

    :Получить список продуктов<
if(Список рекомендаций  пуст?) then(Да) 
    end
    else (Нет) 
    Partition 'Асинхронный запуск через Kafka'
    fork 
    if (В рек-циях есть KK?)  then (Да)
    :Событие: Start KK;
    :Kafka: topic.cc;
    else (Нет) 
endif 

fork again
if (В рек-циях есть KН?) then (Да)
    :Событие: Start KН;
    :Kafka: topic.cn;
    else (Нет)
endif  

fork again
if (В рек-циях есть ДК?) then (Да)
    :Событие: Start ДК;
    :Kafka: topic.dc;
    else (Нет)
endif  
fork end

    :Обновить status = SENT;
    stop


@enduml

