@startuml

skinparam shadowing true
title Процесс создания страницы бренда

|Инициатор|

    start
    :Составить концепцию по новому бренду;
    :Отправить концепцию на согласование>; 

|Директор отдела Одежды|

    :Получить запрос на согласование<
    :Рассмотреть концепцию;
    
    if(Концепция согласована?) then (Нет) 
    #pink :отправть отказ>
    |Инициатор|
    #pink :Получен отказ<
    end
    endif
|Директор отдела Одежды|
    #PaleGreen :ОТправить согласование>

|Инициатор|

    #PaleGreen : Получено согласование<
    :Отправить согласованную заявку на добавление>

|Контент-Менеджер|

    :Получена заявка на добавление<
    :Создать макет бренда на \n текствовом контуре;
    note right :Отдельный подпроцесс \n согласования вида \n страницы нового \n бренда с инициатором
    :Создать страницу нового \n бренда в продовой среде;
    stop


@enduml  