openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /applicationStatus/{applicatoin_id}:
    get:
      summary: Получение статуса заявки
      parameters:
      - name: application_id
        in: path
        description: id заявки для проверки статуса
        schema:
          type: string
          format: uuid

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/applicatoinResponse'
                
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  
  
components:
  schemas:
    applicatoinResponse:
      type: object
      properties:
        application_id:
          type: string
          format: uuid
        application_type:
          type: string
        creation_date:
          type: string
          format: date-time
        status: 
          type: string
          enum:
          - Accepted
          - Pending
          - Approved
          - Declined
          - Confirmed
      required:
      - applicatoin_id
      - application_type
      - creation_date
      - status

    error:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: Description of error response
      required:
        - code
        - message

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'